### PR TITLE
bump deps and use go 1.17

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

# Changes

- KEDA 2.6.1
- Go 1.17
- Kubernetes 0.23.5

### CODE REVIEW

**Comment by zroubalik** [comment]
knative/pkg is not on k8s 0.23 yet :(

**Comment by zroubalik** [comment]
> @zroubalik can you rebase?

@lionelvillard unfortunately knative/pkg is not on k8s 0.23 yet :( So I am waiting till deps are bumped there.

**Comment by pierDipi** [comment]
@zroubalik knaitve/pkg is now on 0.23.4

**Review by pierDipi — COMMENTED** [review]
E2E tests are very limited, did you try it? :fearful:

**Pull request merged**
