### PR TITLE
add ability to scale knative-sandbox/eventing-rabbitmq brokers

### PR DESCRIPTION
**Pull request by vaikas**
Moving from eventing-rabbitmq to here.
https://github.com/knative-sandbox/eventing-rabbitmq/pull/58

### CODE REVIEW

**Comment by zroubalik** [comment]
@vaikas this code expects Eventing Broker already installed in the cluster, right? I wanted to make it more dynamic, so once a new known CRD (Source, Broker) is installed in the cluster, a new dynamic controller is created.

**Comment by vaikas** [comment]
Since it's for Knative based, and only for eventing related matters, do you think the added complexity of waiting dynamically for eventing to be installed before starting (note that its only Broker/Trigger, which get installed when you install Eventing) is worth the added complexity? When you install different Brokers, the only difference will be the BrokerClass annotation that will be controlled by a Broker specific controller. Meaning it's not like the sources/channels which create different kinds of CRDs, there's only two CRDs (Broker/Trigger) which get installed when eventing is installed.

**Comment by zroubalik** [comment]
@vaikas oh you are right! I didn't realize that. Sorry for the confusion.

I'll review this later today. But I don't see why this shouldn't be merged, thanks a lot!

**Pull request merged**
