### PR TITLE
update go 1.15 and k8s 0.19.7

### PR DESCRIPTION
**Pull request by lionelvillard**
# Changes

- in go.mod, use go 1.15, update to k8s 0.19.7 libs, keep replaces
- fix the gnostic OpenAPIv2 openapiv2 stuff
-

<!-

### CODE REVIEW

**Comment by vaikas** [comment]
Thanks for taking care of this. Hope automation works now 👍

**Comment by vaikas** [comment]
Ok, so being impatient, decided to manually just try what the automation does, it does this (unless this repo does something different):
```
vaikas@villes-mbp eventing-autoscaler-keda % ./hack/update-deps.sh --upgrade --release v0.21
=== Update Deps for Golang
--- Upgrading to v0.21
Using 'GOPROXY=direct'.
Floating deps to knative.dev/eventing@master knative.dev/eventing-awssqs@master knative.dev/eventing-kafka@master knative.dev/eventing-redis@master knative.dev/hack@master knative.dev/pkg@master
verifying knative.dev/eventing-awssqs@v0.20.0/go.mod: checksum mismatch
	downloaded: h1:6d0Y+8MPDqiSJtp2X0w5PAlrqu1kOjfgomTZbbwr+Xc=
	go.sum:     h1:RYjhn7/5NIfdUOtgLLSHFVO2kQ6v0zIb+fIcWupU7S8=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
vaikas@villes-mbp eventing-autoscaler-keda % git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Is there a reason why we're fixing these to 0.20 versions instead of floating them like the others?

For example here:
https://github.com/knative-sandbox/eventing-kafka/blob/master/go.mod#L35

@zroubalik I can take a wack at this unless there's a reason to pin them like this.

**Comment by zroubalik** [comment]
@vaikas I don't think there's a particular reason, we can change that. Thanks for doing that!

**Comment by vaikas** [comment]
Ok, here:
https://github.com/knative-sandbox/eventing-autoscaler-keda/pull/73

**Pull request merged**
