### PR TITLE
bug fix for supporting SASL and TLS

### PR DESCRIPTION
**Pull request by steven0711dong**
close https://github.com/knative-sandbox/eventing-autoscaler-keda/issues/41

### CODE REVIEW

**Comment by steven0711dong** [comment]
Will deal with CLA tomorrow

**Comment by zroubalik** [comment]
thanks @steven0711dong!

**Review by zroubalik — COMMENTED** [review]
looking good, just the CLA and linting

**Comment by steven0711dong** [comment]
@zroubalik Thanks for approving. I'm working with my company to het my CLA currently

**Comment by steven0711dong** [comment]
@googlebot I signed it!

**Pull request merged**
