### PR TITLE
bump to KEDA 2.8.1 & introduce Kafka `activationLagThreshold`

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

# Changes

-  :broom: bump KEDA deps to 2.8.1
- :gift: introduce Kafka `activationLagThreshold`

/kind enhancement

**Release Note**

```release-note
bump to KEDA 2.8.1 & introduce Kafka `activationLagThreshold`
```

### CODE REVIEW

**Review by aavarghese — APPROVED** [review]
/lgtm

**Comment by zroubalik** [comment]
Honestly I don't know what to do with the failing Verify check. On my machine the codegen looks good. The reported diff is in the intendation of the generated files, any idea how to fix this? @aavarghese @lionelvillard @matzew @pierDipi ?
```
Found diffs in: third_party/pkg/client/clientset/versioned/fake/register.go
third_party/pkg/client/clientset/versioned/scheme/register.go
Error: Please run ./hack/update-codegen.sh.
diff --git a/third_party/pkg/client/clientset/versioned/fake/register.go b/third_party/pkg/client/clientset/versioned/fake/register.go
index 92f1bb3..6555aa5 100644
--- a/third_party/pkg/client/clientset/versioned/fake/register.go
+++ b/third_party/pkg/client/clientset/versioned/fake/register.go
@@ -37,14 +37,14 @@ var localSchemeBuilder = runtime.SchemeBuilder{
 // AddToScheme adds all types of this clientset into the given scheme. This allows composition
 // of clientsets, like in:
 //
-//	import (
-//	  "k8s.io/client-go/kubernetes"
-//	  clientsetscheme "k8s.io/client-go/kubernetes/scheme"
-//	  aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
-//	)
+//   import (
+//     "k8s.io/client-go/kubernetes"
+//     clientsetscheme "k8s.io/client-go/kubernetes/scheme"
+//     aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
+//   )
 //
-//	kclientset, _ := kubernetes.NewForConfig(c)
-//	_ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
+//   kclientset, _ := kubernetes.NewForConfig(c)
+//   _ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
 //
 // After this, RawExtensions in Kubernetes types will serialize kube-aggregator types
 // correctly.
```

**Comment by pierDipi** [comment]
Hi @zroubalik, I can reproduce it after running `hack/update-codegen.sh` I get this diff:

```
$ git diff
diff --git a/third_party/pkg/client/clientset/versioned/fake/register.go b/third_party/pkg/client/clientset/versioned/fake/register.go
index 92f1bb3a..6555aa50 100644
--- a/third_party/pkg/client/clientset/versioned/fake/register.go
+++ b/third_party/pkg/client/clientset/versioned/fake/register.go
@@ -37,14 +37,14 @@ var localSchemeBuilder = runtime.SchemeBuilder{
 // AddToScheme adds all types of this clientset into the given scheme. This allows composition
 // of clientsets, like in:
 //
-//	import (
-//	  "k8s.io/client-go/kubernetes"
-//	  clientsetscheme "k8s.io/client-go/kubernetes/scheme"
-//	  aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
-//	)
+//   import (
+//     "k8s.io/client-go/kubernetes"
+//     clientsetscheme "k8s.io/client-go/kubernetes/scheme"
+//     aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
+//   )
 //
-//	kclientset, _ := kubernetes.NewForConfig(c)
-//	_ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
+//   kclientset, _ := kubernetes.NewForConfig(c)
+//   _ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
 //
 // After this, RawExtensions in Kubernetes types will serialize kube-aggregator types
 // correctly.
diff --git a/third_party/pkg/client/clientset/versioned/scheme/register.go b/third_party/pkg/client/clientset/versioned/scheme/register.go
index c8c4604d..0882d901 100644
--- a/third_party/pkg/client/clientset/versioned/scheme/register.go
+++ b/third_party/pkg/client/clientset/versioned/scheme/register.go
@@ -37,14 +37,14 @@ var localSchemeBuilder = runtime.SchemeBuilder{
 // AddToScheme adds all types of this clientset into the given scheme. This allows composition
 // of clientsets, like in:
 //
-//	import (
-//	  "k8s.io/client-go/kubernetes"
-//	  clientsetscheme "k8s.io/client-go/kubernetes/scheme"
-//	  aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
-//	)
+//   import (
+//     "k8s.io/client-go/kubernetes"
+//     clientsetscheme "k8s.io/client-go/kubernetes/scheme"
+//     aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
+//   )
 //
-//	kclientset, _ := kubernetes.NewForConfig(c)
-//	_ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
+//   kclientset, _ := kubernetes.NewForConfig(c)
+//   _ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
 //
 // After this, RawExtensions in Kubernetes types will serialize kube-aggregator types
 // correctly.

```

**Comment by pierDipi** [comment]
Do you have go 1.18 installed?

**Review by aavarghese — APPROVED** [review]
/lgtm

**Pull request merged**
